### ISSUE TITLE
Registration marks not working on Portrait

### ISSUE THREAD

**Issue by Robin2** [fablabnbg/inkscape-silhouette#32]
There is already a closed issue about Registration Marks. I cannot tell from it whether anyone got them to work and I don't know why that issues was closed.

Anyway, they are not working for me. Every time I tried the reg marks with this program it failed to find them even with various changes to the distances.
When I tried using reg marks with RoboCut (using its own template) it found the marks but the cutting was lozenged compared with my printed boxes. Having successfully printed using the Silhouette software on Windows I suspect the template has the marks in the wrong place. The Silhouette software says it places them 15.9mm in from the edges of the paper.

I am interested to do some exploring with the Portrait over the next few weeks. Is there any discussion  group or Forum that I could learn from and contribute to?

...R

**Comment by EtherGraf** [comment]
If you need registration marks, then be sure to test with the forked registration marks branch from me. I have not found yet the time to release it into trunk, but it works well for me. The registration marks in master branch does currently NOT work!

https://github.com/EtherGraf/inkscape-silhouette/tree/registrationmarks

Some small discussion you can find in pull request #25

**Comment by Robin2** [comment]
Thanks very much. Your version seems to solve the problem.
Two small points ...
- For my Portrait I needed to swap the dimensions 180 and 230
- When it finishes it stops at the wrong end of the page - near 0,0 rather than 0,297

Also, I "think" the cutter uses the inside edges of the reg marks as the reference points but Inkscape makes it difficult to position them accurately.

...R

**Comment by EtherGraf** [comment]
Thanks for your feedback.

Are there the wrong default values set, or where do you have to swap the values 180 and 230? Can you tell exactly, which values you have to enter where?

The final stop position is currently missing in my branch, I will have to remerge it with the trunk. At some point there was the possibility to select the stop position...

I have never researched the exact reference of the regmark, but would have expected for practical reasons to be in the middle of the line. The reference on the top left box must be outside, because there is no 'inside'. Would be interesting to do some variants with thicker marks.

N.B. To set positions in inkscape acurately, use the value fields with the numeric coordinate values.

**Comment by Robin2** [comment]
When you click "send to silhouette and open the Regmarks tab there are two entries
X mark distance 180 and Y mark distance 230. I needed to swap them around when I tried your version **for the first time**.
But I did another test just now after deleting your inkscape-silhouette files from the extensions folder and re-copying them in from the un-zipped version and it worked fine **without** needing to swap them round. I wonder if the problem earlier was because it was still using older settings - I had a sense, yesterday, that it did that with some other setting, but I can think of no reason why it should.

For the moment you should assume that the X and Y lengths are actually correct. Apologies for the confusion.

I have been planning to do some tests with 5mm thick reg marks so the effect of the thickness is very obvious - and I have been using the value fields. I have used Open Office Draw quite a lot and Inkscape is fairly similar.

I do a good bit of Arduino programming and I think it is much more likely that the regmarks use the change from light to dark for precise positioning. Also I printed the reg marks with Silhouette Studio which had specified their position and it seemed to correspond with the inside edges of the marks (i.e. the edges nearest the centre of the paper).

I am hoping to make a little platform to sit the Portrait on so I can accurately align the paper without needing reg marks. If you want to produce a complete A4 image you don't want dirty great marks at the corners :)

...R

**Comment by Robin2** [comment]
Update ...
I tried some tests with registration marks 5mm thick and it did not work at all
With 1mm marks it works fine and, contrary to my earlier speculation it seems to use the outside of the reg marks for the registration point. With OpenOfficeDraw it is easy to select which side of an object the measurements are taken from.
It also worked fine with 0.3mm reg marks

My attempts to physically align the paper have come to nothing. I don't think it is possible to guarantee that it will pull the paper in perfectly straight. I had been hoping it would be possible to make something like a printed birthday-card with cut-outs while using the whole A4 sheet.

...R

**Comment by EtherGraf** [comment]
I have just started the window software in a vm and observed, that the line thickness could be set from 0.3mm to 1.0mm. If I show the cutting area too, then it goes through the center of the regmarks. Even the box in the left upper side seems to have a 'border thickness' . Possibly this thickness is corrected on the device, because it is sent in the code to the device. At the moment it is hardcoded to 0.5mm.

Another Idea for you: Create a cutting matt yourself a little bigger than A4, print the regmarks on it and mark the area of an A4 sheet. Place your card precisely on this area and start cutting.

**Comment by EtherGraf** [comment]
Btw. The template registration-marks-a4-maxi.svg does not work correctly, because the offset seemingly must be >= 10mm.

**Comment by Robin2** [comment]
That's a clever idea - putting the marks on the mat. However the sheet to be cut would need to be clear of the reg marks and with my Portrait I don't think I could get the full A4 size. 

Based on something a guy from Graphtec said I successfully made a mat from a piece of card sprayed with 3M Spray Mount.

I will do some more tests with the positioning of the reg marks.

Yesterday I was creating my drawings with LibreOffice Draw which, by default, includes a border around objects. When I turned off the border the sizes were more accurate.

...R

**Comment by EtherGraf** [comment]
You definitely could process a complete A4 sheet with a slightly bigger mat on a portrait device. Thats what I am doing currently. My selfmade mat (File register with UHU spray mount) is on both sides 5 mm oversized. Maybe not enough for regmarks. You have to use it in portrait orientation, not in landscape.

**Comment by Robin2** [comment]
Yes, I tend to forget that it is not limited to the length of an A4 page. I have a few large sheets of card. I must try making a long mat.

I did some more tests about the positioning of the reg marks and I am not really any wiser - or even as wise as I thought I was. For example I tried using 1mm thick marks aligned to their outer edges (i.e away from the page centre) and also using 0.3mm marks aligned in the same way and the same place. I thought that would show a difference if the Portrait was using the centre of the marks as the registration point. I also tried setting the 1mm marks by their centre points. Truthfully I could not really tell the difference. I think the 0.3mm marks gave slightly better results so that is what I will use. Again, apologies for any confusion.

And just to be clear, for any other readers, the registration marks are working very well with the Ethergraf version.

...R

**Comment by Robin2** [comment]
Do the recent changes to this version (from 3 days ago) make the registration marks work properly?

...R

**Comment by penguineer** [comment]
They do not work for me. 

The cameo scans for reg marks (and finds them), but then does nothing.

Running inkscape on terminal shows the following:
```
Silhouette Portrait found on usb bus=1 addr=7
status=ready
device version: 'Portrait V1.10   '
7 self.docHeight= 1052.3622
8 self.docWidth= 744.09448
FG: 'Portrait V1.10    '
Media=122, cap='yellow', name='Cardstock 40-60 lbs (90g)'
speed: 10
pressure: 30
Loaded media is expected left-aligned.
mediabox: (0,0)-(203,297)
bb regoriginx=10 regoriginy=15
0% (+100%) bbox: (20.1,42.1)-(166.9,251.9)mm, 71 points
0% (+100%) .
status=moving
 done. 0 min 24 sec
```



I have to take back the below description. I updated the git repo, but Inkscape used different files. Fixed now.
+++


Problem is that the USB connection seems to time out (set 20 s, but my Portrait takes a bit longer to scan for registration marks).

However, it scans in the area of the registration marks and seems to find them.

```
Traceback (most recent call last):
  File "sendto_silhouette.py", line 1100, in <module>
    e.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "sendto_silhouette.py", line 1040, in effect
    regwidth=self.options.regwidth,reglength=self.options.reglength)
  File "/home/tux/.config/inkscape/extensions/silhouette/Graphtec.py", line 709, in plot
    resp = s.read(timeout=40000) ## Allow 20s for reply...
  File "/home/tux/.config/inkscape/extensions/silhouette/Graphtec.py", line 337, in read
    data = s.dev.read(endpoint, size, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/usb/core.py", line 670, in read
    self.__get_timeout(timeout)
  File "/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 780, in bulk_read
    timeout)
  File "/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 889, in __read
    _check(retval)
  File "/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 571, in _check
    raise USBError(_str_error[ret], ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out
```

**Comment by EtherGraf** [comment]
From the line numbers in the exception I can see, you are not using the 
latest version. Could you please try with a recent one?

What does happen, if you try registration marks with a smaller distance, 
so that the timeout does not occur?
The comment in the code ist wrong, the real timeout argument means 40s!

Also try to rotate your paper very slightly clockwise. With exact 
orientation I have sometimes problems too. Reason unknown.

**Comment by penguineer** [comment]
Please ignore everything after "I have to take back the below description." I just left it there because that was the original post and I was not sure if anyone had already read it. Your analysis is right, I had an old version, which was fixed for the first part of the comment.

So right now: Registration marks seem to be found (I can watch them being scanned), but after that cutting does not take place. 

When I remove the option to find registration marks, cutting takes place, but not aligned.

The timeout does not occur anymore.

**Comment by EtherGraf** [comment]
What device type do you own?
Its not clear from your comments: There you mention a cameo. The debug 
print contrary shows 'Portrait V1.10'. Not sure if this means anything.

**Comment by penguineer** [comment]
The Device shows as 'Portrait V1.10', I bought it as Silhouette America Portrait.
(Sorry for bringing in the Cameo, that was an accident.)

**Comment by lexelby** [comment]
@EtherGraf Is this kind of like what you were describing, a cutting mat that has registration marks on it? https://www.amazon.com/Silhouette-PixScan-Cutting-Mat-Portrait/dp/B00CICZ5XU/

**Comment by EtherGraf** [comment]
No, its the same registration marks but another idea.
You can use this to cutout precisely a contour of a drawing.

My idea is to print the registration marks with all other content (drawings or whatever) on a sheet of paper. The plotter can use this marks to exactly reference your paper and follow exactly the contours.
For this there are some templates with registration marks.

If you have to do a referenced cut, without the possibility to print registration marks, you can use this cutting mat, but then you have to reference somehow your working piece to the cutting mat. This can be done e.g. by scanning the mat with sticked working piece. This is, what the brother software does.

**Comment by CarlosGS** [comment]
I was just bit by this issue; however the problem is not only within the templates, it is due to the last release of inkscape-silhouette being too old.

With the Debian package currently provided, the X/Y offsets are inverted and the machine cannot find the marks properly (as @Robin2 pointed out). **It is fixed by manually installing the plugin from this github repository.** (see _Installation -> Other Debian based Linux_)

The template that worked for me is from @EtherGraf  https://github.com/EtherGraf/inkscape-silhouette/blob/registrationmarks/examples/registration-marks.svg

Ideally, we could have a new release with a new .deb file that incorporates the latest work :-)

**Comment by EtherGraf** [comment]
The template mentioned was merged already into the master branch on fablabnbg:
https://github.com/fablabnbg/inkscape-silhouette/blob/master/examples/registration-marks-cameo-silhouette-a4-maxi.svg

You are right, a new release should be considered. 
@jnweiger could you have a look at the latest pull requests and create a new release?

**Comment by stephanedaviet** [comment]
I always got a slight problem with those registration marks. If I set in the settings window *Position of regmarks from document left|top [mm]* to 10mm, I always end up with the message: *Couldn't find registration marks*. Thus, I increase the setting to 10,4mm for each so that the Silhouette move a bit more and detects the marks. It works, the Silhouette Portrait detects the registration marks, but the cutting is 0,4 aside what's printed :-/. I have tested with and without a cutting mat.

What I don't understand, if the Silhouette detects registration marks, even with those slightly displaced settings, why it doesn't take it into account to adjust its cutting so that it matches the position of detected registration marks and thus the printing? What's the use of those registration marks then?

**Comment by stephane-daviet-maif** [comment]
I was still having a problem with those registration marks. If I set in the settings window *Position of regmarks from document left|top [mm]* to 10mm, I always end up with the message: *Couldn't find registration marks*. Thus, I increase the setting to 10,4mm for each so that the Silhouette move a bit more and detects the marks. It works, the Silhouette Portrait detects the registration marks, but the cutting is 0,4 aside what's printed.

The solution I found on a blog is to insert the cutting mat so that the black square is in front of the blade, sligthly translated on the left (approximately 5mm). Then it works like a charm with the latest version of the reg marks available on the repo.
